trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  dotnetSdkVersion: '8.0.x'
  azureServiceConnection: 'svc-conn-1rad-dev'
  webAppName: '1RadAPI'
  apiProject: '1RadAPI/1RadAPI.csproj'
  testProjects: '1Rad.UnitTests/1Rad.UnitTests.csproj'
  publishDir: '$(Build.ArtifactStagingDirectory)/publish'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '$(dotnetSdkVersion)'

- task: DotNetCoreCLI@2
  displayName: 'Restore API'
  inputs:
    command: 'restore'
    projects: '$(apiProject)'

- task: DotNetCoreCLI@2
  displayName: 'Build API'
  inputs:
    command: 'build'
    projects: '$(apiProject)'
    arguments: '--configuration $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: 'test'
    projects: '$(testProjects)'
    arguments: '--configuration $(buildConfiguration) --no-build'
    publishTestResults: true

- task: DotNetCoreCLI@2
  displayName: 'Publish API'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(apiProject)'
    arguments: '--configuration $(buildConfiguration) --output $(publishDir)'
    zipAfterPublish: true

- task: AzureWebApp@1
  displayName: 'Deploy to Dev App Service'
  inputs:
    azureSubscription: '$(azureServiceConnection)'
    appType: 'webApp'
    appName: '$(webAppName)'
    package: '$(publishDir)/**/*.zip'